# Generated by Django 4.2.16 on 2025-03-07 17:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_post_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heading',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='headings', to='blog.post'),
        ),
        migrations.AlterField(
            model_name='heading',
            name='slug',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
