# Generated by Django 4.2.16 on 2025-03-07 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_heading_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(max_length=256),
        ),
        migrations.AlterField(
            model_name='heading',
            name='slug',
            field=models.SlugField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(max_length=128),
        ),
    ]
