# Generated by Django 4.2.16 on 2025-03-12 21:31

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_alter_category_slug_alter_heading_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heading',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
